json.id shelter.id
json.name shelter.name 
json.specialty shelter.specialty
json.email shelter.contact_info.email
json.phone_number shelter.contact_info.phone_number
json.address shelter.contact_info.address
json.city shelter.contact_info.city
json.state shelter.contact_info.state
json.zip shelter.contact_info.zip